numOfAlgebraLinearFactorization=1
numOfAlgebraLinearFactorization3=1
numOfAlgebraLogarithmRules=1
numOfAlgebraQuadraticEquation=1
numOfArithmeticAddition=1
numOfArithmeticSubstraction=1
numOfDifferentialRules=1
numOfFunctionsInverse=1
numOfIntegralDefinite=1
numOfIntegralRules=1
numOfStereoCalculations=1
numOfStereoRules=1
numOfStereoSphereSurfaceVolume=1
numOfStereoSphereVolume=1
numOfStochasticBernoulliExperiment=1
numOfStochasticCombination=1
numOfTrigonometryRules=1
numOfVectorCrossProduct=1
numOfVectorDotProduct=1
