numOfAddition=0
numOfMcAddition=0
numOfMcAlgebraLinearFactorization=0
numOfMcAlgebraLinearFactorization3=0
numOfMcAlgebraQuadraticEquation=0
numOfMcStochasticBernoulliExperiment=1
numOfMcStochasticCombination=0
numOfMcStereoSphereSurfaceAreaVolume=0
numOfMcStereoSphereVolume=0